# Welcome to Epeolatory.in!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Epeolatry.in | You're bound to find more.
logo:               /images/pages/logo.png
description:        Book Reviews, Poetries, Writer's Corner
baseurl:            ''
url:                'https://epeolatry.in'

# Social Settings
twitter:            
facebook:           https://www.facebook.com/epeolatry.in
instagram:          https://www.instagram.com/bookworm_falguni
amazon:             https://www.amazon.in/gp/profile/amzn1.account.AGWBO4A7KCKFKSVTS2VODO64KUDQ?ie=UTF8&ref_=ya_mb_l_prf
goodreads:          https://www.goodreads.com/user/show/58171261-falguni-jain
linkedin:           https://www.linkedin.com/in/falguni-jain-40a4bb155/

disqus_shortname:   epeolatory
gtag: G-KLZYMBKREY

markdown:  kramdown
permalink: pretty
autopages:
  enabled: false
pagination:
  enabled: true
  debug: true
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 2
sass:
  style: compact
  sass_dir: _sass

gems:
  - jekyll-paginate-v2
  - jekyll/tagging
  - jekyll-minifier
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-menus

plugins:
  - jekyll-paginate-v2
  - jekyll/tagging
  - jekyll-minifier
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-menus

include:
  - _pages
  - _sass/vendor/fa/webfonts

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

jekyll-minifier:
  uglifier_args:
    harmony: true

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
      sitemap:
        tags:
          changefreq: weekly
          priority: 0.7
  - scope:
      path: 'tag'
    values:
      sitemap:
        tags:
          changefreq: daily
          priority: 0.5
  - scope:
      path: ""
      type: "posts"
    values:
      sitemap:
        tags:
          changefreq: weekly
          priority: 0.9