# Welcome to Epeolatory.in!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Epeolatry.in | You're bound to find more.
logo:               /images/pages/logo.png
description:        Book Reviews, Poetries, Writer's Corner
baseurl:            ''
url:                'https://epeolatry.in'
twitter:            https://twitter.com/epeolatry
facebook:           https://www.facebook.com/epeolatry
instagram:          https://www.instagram.com/epeolatry

markdown:  kramdown
permalink: pretty
paginate:  12
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext