# This is a basic workflow to help you get started with Actions

name: CD

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Standard usage
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    
    - uses: limjh16/jekyll-action-ts@v2
      with:
        enable_cache: true

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages
